fix build on clang
It was an error:

src/build/galera-src/gcs/src/gcs_group.cpp:1666:16: error: 'char* strncpy(char*, const char*, size_t)' output may be truncated copying 36 bytes from a string of length 36 [-Werror=stringop-truncation]
         strncpy(entries[i].uuid, node.id, WSREP_UUID_STR_LEN);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/src/build/galera-src/galera/src/replicator_smm_stats.cpp:253:12: error: 'char* strncpy(char*, const char*, size_t)' specified bound 64 equals destination size [-Werror=stringop-truncation]
     strncpy(interval_string_, osinterval.str().c_str(), sizeof(interval_string_));

Because of the error -Wno-stringop-truncation was added, but it broke clang builds